from tkinter import *
a=Tk()
B1=Button(a,text="error",relief=RAISED,bitmap="error")
B2=Button(a,text="hourglass",relief=RAISED,bitmap="hourglass")
B3=Button(a,text="info",relief=RAISED,bitmap="info")
B4=Button(a,text="question",relief=RAISED,bitmap="question")
B5=Button(a,text="warning",relief=RAISED,bitmap="warning")
B6=Button(a,relief=RAISED,bitmap="questhead",bg="sky blue")
B7=Button(a,relief=RAISED,bitmap="gray12",bg="blue")
B8=Button(a,relief=RAISED,bitmap="gray25",bg="magenta")
B9=Button(a,relief=RAISED,bitmap="gray50",bg="orange")
B10=Button(a,relief=RAISED,bitmap="gray75",bg="white")
B1.pack()
B2.pack()
B3.pack()
B4.pack()
B5.pack()
B6.pack()
B7.pack()
B8.pack()
B9.pack
B10.pack()
a.mainloop()